Container: container_1761119194299_0025_01_000001 on vm-99230800_40415
LogAggregationType: AGGREGATED
======================================================================
LogType:stdout-active
LogLastModifiedTime:Wed Oct 22 09:03:15 +0000 2025
LogLength:2893
LogContents:
2025-10-22 09:03:09,910 INFO UserConsole [redirect output]: 2025-10-22 09:03:09 | INFO: Arguments instantiated: {'run_id': '1a1c243c-b1ec-4778-9642-348edc4f3b45', 'key_vault_name': 'MetEdwKeyVaultProd', 'key_vault_linked_service_name': 'MET_EDW_KeyVault', 'sql_password_secret_name': 'ProcfwkSqlDbPassword', 'sql_host_name': 'bdaprodsql.public.35133d2c7131.database.windows.net', 'sql_port': '3342', 'sql_database': 'S_procfrwk', 'sql_user': 'procfwk-user', 'source_data_source': [], 'target_data_source': 'domain_finance', 'load_definitions': [], 'restart': None, 'sequential': None}

2025-10-22 09:03:15,101 INFO UserConsole [redirect output]: Traceback (most recent call last):
  File "/mnt/var/hadoop/tmp/nm-local-dir/usercache/trusted-service-user/appcache/application_1761119194299_0025/container_1761119194299_0025_01_000001/main.py", line 302, in <module>

2025-10-22 09:03:15,168 INFO UserConsole [redirect output]:     from spark_helpers import functions as func
  File "spark_helpers.zip/spark_helpers/functions.py", line 12, in <module>
  File "/home/trusted-service-user/cluster-env/env/lib/python3.10/site-packages/azure/storage/blob/__init__.py", line 10, in <module>
    from ._blob_client import BlobClient
  File "/home/trusted-service-user/cluster-env/env/lib/python3.10/site-packages/azure/storage/blob/_blob_client.py", line 59, in <module>
    from ._download import StorageStreamDownloader
  File "/home/trusted-service-user/cluster-env/env/lib/python3.10/site-packages/azure/storage/blob/_download.py", line 20, in <module>
    from ._encryption import (
  File "/home/trusted-service-user/cluster-env/env/lib/python3.10/site-packages/azure/storage/blob/_encryption.py", line 21, in <module>
    from cryptography.hazmat.primitives.ciphers import Cipher
  File "/home/trusted-service-user/cluster-env/env/lib/python3.10/site-packages/cryptography/hazmat/primitives/ciphers/__init__.py", line 11, in <module>
    from cryptogr
2025-10-22 09:03:15,168 INFO UserConsole [redirect output]: aphy.hazmat.primitives.ciphers.base import (
  File "/home/trusted-service-user/cluster-env/env/lib/python3.10/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 10, in <module>
    from cryptography.exceptions import (
  File "/home/trusted-service-user/cluster-env/env/lib/python3.10/site-packages/cryptography/exceptions.py", line 9, in <module>

2025-10-22 09:03:15,173 INFO UserConsole [redirect output]:     from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
ImportError: /home/trusted-service-user/cluster-env/env/lib/python3.10/lib-dynload/../../libcrypto.so.3: version `OPENSSL_3.3.0' not found (required by /home/trusted-service-user/cluster-env/env/lib/python3.10/site-packages/cryptography/hazmat/bindings/../../../../../libssl.so.3)

2025-10-22 09:03:15,478 INFO UserConsole [pool-42-thread-1]: Calling LA appender v2 Stop...


End of LogType:stdout-active
******************************************************************************

